"""create event and outbox tables

Revision ID: 76d283d4db3d
Revises: 
Create Date: 2026-09-21 22:09:44.792853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d283d4db3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.Text(), nullable=False),
    sa.Column('received_at', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=False),
    sa.Column('causation_id', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('source_event_id', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('event_seq'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_causation', ['causation_id'], unique=False)
        batch_op.create_index('idx_events_correlation', ['correlation_id'], unique=False)
        batch_op.create_index('idx_events_source_event', ['source', 'source_event_id'], unique=False)
        batch_op.create_index('idx_events_source_seq', ['source', 'event_seq'], unique=False)
        batch_op.create_index('idx_events_type_seq', ['event_type', 'event_seq'], unique=False)
        batch_op.create_index('uq_events_source_dedupe', ['source', 'dedupe_key'], unique=True, sqlite_where=sa.text('dedupe_key IS NOT NULL'))
        batch_op.create_index('uq_events_source_event', ['source', 'source_event_id'], unique=True, sqlite_where=sa.text('source_event_id IS NOT NULL'))

    op.create_table('outbox',
    sa.Column('outbox_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'PUBLISHED')", name='ck_outbox_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_outbox_attempt_count'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('outbox_id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index('idx_outbox_pending', ['status', 'next_attempt_at', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index('idx_outbox_pending')

    op.drop_table('outbox')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('uq_events_source_event', sqlite_where=sa.text('source_event_id IS NOT NULL'))
        batch_op.drop_index('uq_events_source_dedupe', sqlite_where=sa.text('dedupe_key IS NOT NULL'))
        batch_op.drop_index('idx_events_type_seq')
        batch_op.drop_index('idx_events_source_seq')
        batch_op.drop_index('idx_events_source_event')
        batch_op.drop_index('idx_events_correlation')
        batch_op.drop_index('idx_events_causation')

    op.drop_table('events')
    # ### end Alembic commands ###
